# Generated by Django 3.0.3 on 2020-02-12 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
